### PR TITLE
Delete package folder after failed ensure

### LINKED ISSUE #193: Repository is empty while pulling from cached copy
It seems the cached copies of dependency repositories are becoming empty somehow:

```
WARN: failed to ensure package github.com/sampctl/samp-stdlib: failed to ensure dependency from cache: remote repository is empty
```

### PR DESCRIPTION
**Pull request by ADRFranklin**
closes #193

### CODE REVIEW

File: rook/ensure.go [hunk 1]
```diff
@@ -104,7 +104,12 @@ func (pcx *PackageContext) EnsurePackage(meta versioning.DependencyMeta, forceUp
 		print.Verb(meta, "need to clone new copy from cache")
 		repo, err = pcx.EnsureDependencyFromCache(meta, dependencyPath, false)
 		if err != nil {
-			return errors.Wrap(err, "failed to ensure dependency from cache")
+			errors.Wrap(err, "failed to ensure dependency from cache")
+			err2 := os.RemoveAll(dependencyPath)
+			if err2 != nil {
+				return errors.Wrap(err, "failed to remove corrupted dependency repo")
+			}
+			return
```
Comment (Southclaws) [inline rook/ensure.go:112]: It's worth doing some kind of retry logic here, just so the user doesn't have to run it twice. Mainly because the user has no idea that this error is non-idempotent and may behave differently on a second run.

File: rook/ensure.go [hunk 2]
```diff
@@ -32,12 +34,21 @@ func (pcx *PackageContext) EnsureDependencies(ctx context.Context, forceUpdate b
...
+			errInner := pcx.EnsurePackage(dependency, forceUpdate)
+			if errInner != nil {
+				print.Warn(errors.Wrapf(errInner, "failed to ensure package %s", dependency))
+				return errInner
+			}
+			print.Info(pcx.Package, "successfully ensured dependency files for", dependency)
+			return nil
+		})
+		if err != nil {
+			print.Warn("failed to ensure package '", dependency, "' after 2 attempts, skipping")
```
Comment (Southclaws) [inline rook/ensure.go:49]: If this is intended to ignore the error ("skipping") then log the error and set `err` to `nil`. Otherwise, let it be returned.
